# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

before_install:
  - ./test/customize_environment.sh

install:
  - ./src/os/setup.sh -y

language: generic

matrix:
  include:

    - os: linux
      dist: trusty

    - os: linux
      dist: yakkety

script:
  - ./test/main.sh

sudo: required
