#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="vim --"
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -l"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"
alias rm="rm -rf --"
alias t="tmux"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias dl="cd ~/Downloads"
alias pp="cd /media/mickael/Data/Projects/MPinheiro"
alias pi="cd /media/mickael/Data/Projects/IPLeiria"

alias giti='git config --local user.name "Michael Pinheiro"; git config --local user.email "michael.pinheiro@ipleiria.pt"'
alias gitp='git config --local user.name "Michael Pinheiro"; git config --local user.email "mickael.pinheiro@gmail.com"'


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

. "aliases/$OS/bash_aliases"





